pull_request_rules:
  # approve
  - name: automatic approval
    conditions:
      - author=dsm23
      - check-success=check
      - check-success=test
      - check-success=analyze
      - "#check-success>=7"
    actions:
      review:
        type: APPROVE
        message: Automatically approving dsm23
  - name: automatic approval for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=check
      - check-success=test
      - check-success=analyze
      - "#check-success>=7"
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot
  # merge
  - name: Automatically merge when GitHub Actions jobs succeed
    conditions:
      - check-success=check
      - check-success=test
      - check-success=analyze
      - "#check-success>=7"
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
